name: Build PivotOS
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PivotOS
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - run: sudo apt-get install xorriso
      - run: zig build
