name: Build PivotOS
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PivotOS
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - run: sudo apt-get install xorriso
      - run: zig build
