name: Build PivotOS
on:
  pull_request:
    types: [opened, review_requested, ready_for_review, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PivotOS
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Read Zig version
        id: zig-version
        run: echo "version=$(cat .zigversion)" >> $GITHUB_OUTPUT
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ steps.zig-version.outputs.version }}
      - run: sudo apt-get install xorriso
      - run: zig build
