name: Build PivotOS
run-name: Build PivotOS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PivotOS
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - run: zig build
