name: Build PivotOS
on:
  pull_request:
    types: [opened, review_requested, ready_for_review, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PivotOS
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.3237+ddff1fa4c
      - run: sudo apt-get install xorriso
      - run: zig build
